// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoMigrate() {
  return window['go']['controller']['DBController']['AutoMigrate']();
}

export function CheckConnect() {
  return window['go']['controller']['DBController']['CheckConnect']();
}

export function Connect(arg1) {
  return window['go']['controller']['DBController']['Connect'](arg1);
}

export function CreateAccounts(arg1) {
  return window['go']['controller']['DBController']['CreateAccounts'](arg1);
}

export function CreatePlatforms(arg1) {
  return window['go']['controller']['DBController']['CreatePlatforms'](arg1);
}

export function CreateSettings(arg1) {
  return window['go']['controller']['DBController']['CreateSettings'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['controller']['DBController']['DeleteAccount'](arg1);
}

export function DeletePlatform(arg1) {
  return window['go']['controller']['DBController']['DeletePlatform'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['controller']['DBController']['DeleteSetting'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['controller']['DBController']['GetAccount'](arg1);
}

export function GetPlatform(arg1) {
  return window['go']['controller']['DBController']['GetPlatform'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['controller']['DBController']['GetSetting'](arg1);
}

export function QueryAccounts(arg1) {
  return window['go']['controller']['DBController']['QueryAccounts'](arg1);
}

export function QueryPlatforms(arg1) {
  return window['go']['controller']['DBController']['QueryPlatforms'](arg1);
}

export function QuerySettings(arg1) {
  return window['go']['controller']['DBController']['QuerySettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['controller']['DBController']['SetContext'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['controller']['DBController']['UpdateAccount'](arg1);
}

export function UpdatePlatform(arg1) {
  return window['go']['controller']['DBController']['UpdatePlatform'](arg1);
}

export function UpdateSetting(arg1) {
  return window['go']['controller']['DBController']['UpdateSetting'](arg1);
}
