// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {context} from '../models';

export function AutoMigrate():Promise<void>;

export function CheckConnect():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function CreateAccounts(arg1:Array<db.Account>):Promise<Array<db.Account>>;

export function CreatePlatforms(arg1:Array<db.Platform>):Promise<Array<db.Platform>>;

export function CreateSettings(arg1:Array<db.Setting>):Promise<Array<db.Setting>>;

export function DeleteAccount(arg1:db.Account):Promise<void>;

export function DeletePlatform(arg1:db.Platform):Promise<void>;

export function DeleteSetting(arg1:db.Setting):Promise<void>;

export function GetAccount(arg1:db.Account):Promise<db.Account>;

export function GetPlatform(arg1:db.Platform):Promise<db.Platform>;

export function GetSetting(arg1:db.Setting):Promise<db.Setting>;

export function QueryAccounts(arg1:{[key: string]: any}):Promise<Array<db.Account>>;

export function QueryPlatforms(arg1:{[key: string]: any}):Promise<Array<db.Platform>>;

export function QuerySettings(arg1:{[key: string]: any}):Promise<Array<db.Setting>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateAccount(arg1:db.Account):Promise<db.Account>;

export function UpdatePlatform(arg1:db.Platform):Promise<void>;

export function UpdateSetting(arg1:db.Setting):Promise<void>;
