// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';

export function CloseBrowser():Promise<void>;

export function GetCookiePath(arg1:string):Promise<string>;

export function GetPlatformConfigPath(arg1:string):Promise<string>;

export function SaveCookies(arg1:Array<proto.NetworkCookie>,arg2:string):Promise<void>;

export function StartBrowser(arg1:boolean):Promise<void>;
