// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser() {
  return window['go']['controller']['RODController']['CloseBrowser']();
}

export function GetCookiePath(arg1) {
  return window['go']['controller']['RODController']['GetCookiePath'](arg1);
}

export function GetPlatformConfigPath(arg1) {
  return window['go']['controller']['RODController']['GetPlatformConfigPath'](arg1);
}

export function SaveCookies(arg1, arg2) {
  return window['go']['controller']['RODController']['SaveCookies'](arg1, arg2);
}

export function StartBrowser(arg1) {
  return window['go']['controller']['RODController']['StartBrowser'](arg1);
}
