// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser():Promise<void>;

export function StartBrowser(arg1:boolean):Promise<void>;
