// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser() {
  return window['go']['controller']['RODController']['CloseBrowser']();
}

export function StartBrowser(arg1) {
  return window['go']['controller']['RODController']['StartBrowser'](arg1);
}
