// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArticlesInfo() {
  return window['go']['application']['ATApp']['GetArticlesInfo']();
}

export function LoadArticles(arg1, arg2) {
  return window['go']['application']['ATApp']['LoadArticles'](arg1, arg2);
}

export function Run() {
  return window['go']['application']['ATApp']['Run']();
}

export function StartUp(arg1) {
  return window['go']['application']['ATApp']['StartUp'](arg1);
}

export function SyncSelectPlatforms(arg1) {
  return window['go']['application']['ATApp']['SyncSelectPlatforms'](arg1);
}
