// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {context} from '../models';

export function GetArticlesInfo():Promise<Array<utils.Article>>;

export function LoadArticles(arg1:string,arg2:string):Promise<Array<utils.Article>>;

export function Run():Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;

export function SyncSelectPlatforms(arg1:Array<utils.Article>):Promise<void>;
