// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {controller} from '../models';
import {context} from '../models';

export function GetArticlesInfo():Promise<Array<utils.Article>>;

export function HasController():Promise<boolean>;

export function InitConfig():Promise<void>;

export function LoadArticles(arg1:string,arg2:string):Promise<Array<utils.Article>>;

export function Publish():Promise<void>;

export function RefreshPlatforms():Promise<void>;

export function SetController(arg1:controller.DBController,arg2:controller.RODController):Promise<void>;

export function SetPlatforms(arg1:Array<any>):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;

export function SyncPlatformsInfoFromRemote(arg1:string):Promise<void>;

export function SyncSelectPlatforms(arg1:Array<utils.Article>):Promise<void>;
