// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigDir() {
  return window['go']['utils']['CommonUtils']['GetConfigDir']();
}

export function GetConfigFilePath() {
  return window['go']['utils']['CommonUtils']['GetConfigFilePath']();
}

export function LoadJSONFile(arg1) {
  return window['go']['utils']['CommonUtils']['LoadJSONFile'](arg1);
}

export function OpenDir(arg1) {
  return window['go']['utils']['CommonUtils']['OpenDir'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['utils']['CommonUtils']['OpenFile'](arg1);
}

export function ReadJSONFile(arg1) {
  return window['go']['utils']['CommonUtils']['ReadJSONFile'](arg1);
}

export function SaveJSONFile(arg1, arg2) {
  return window['go']['utils']['CommonUtils']['SaveJSONFile'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['utils']['CommonUtils']['SetContext'](arg1);
}
