// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetConfigDir():Promise<string>;

export function GetConfigFilePath():Promise<string>;

export function LoadJSONFile(arg1:string):Promise<{[key: string]: any}>;

export function OpenDir(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<string>;

export function SaveJSONFile(arg1:string,arg2:{[key: string]: any}):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
