// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {db} from '../models';
import {utils} from '../models';
import {context} from '../models';

export function CheckAuthentication():Promise<{[key: string]: string}>;

export function CheckConfig(arg1:any):Promise<void>;

export function HasAccount():Promise<boolean>;

export function HasDBController():Promise<boolean>;

export function HasRODController():Promise<boolean>;

export function InitRod(arg1:controller.DBController,arg2:controller.RODController,arg3:any):Promise<void>;

export function LoadConfig():Promise<{[key: string]: any}>;

export function Login():Promise<db.Account>;

export function OpenPage(arg1:string,arg2:number):Promise<void>;

export function Publish():Promise<void>;

export function SetAccount(arg1:db.Account,arg2:utils.AccountInfo):Promise<void>;

export function SetArticle(arg1:utils.Article):Promise<void>;

export function SetController(arg1:controller.DBController,arg2:controller.RODController):Promise<void>;

export function Start(arg1:context.Context,arg2:controller.DBController,arg3:controller.RODController,arg4:any,arg5:db.Account,arg6:utils.Article,arg7:utils.AccountInfo,arg8:any):Promise<void>;

export function UpdatePlatformInfo():Promise<void>;
