// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthentication() {
  return window['go']['platforms']['RodCSDN']['CheckAuthentication']();
}

export function CheckConfig(arg1) {
  return window['go']['platforms']['RodCSDN']['CheckConfig'](arg1);
}

export function HasAccount() {
  return window['go']['platforms']['RodCSDN']['HasAccount']();
}

export function HasDBController() {
  return window['go']['platforms']['RodCSDN']['HasDBController']();
}

export function HasRODController() {
  return window['go']['platforms']['RodCSDN']['HasRODController']();
}

export function InitRod(arg1, arg2, arg3) {
  return window['go']['platforms']['RodCSDN']['InitRod'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['platforms']['RodCSDN']['LoadConfig']();
}

export function Login() {
  return window['go']['platforms']['RodCSDN']['Login']();
}

export function OpenPage(arg1) {
  return window['go']['platforms']['RodCSDN']['OpenPage'](arg1);
}

export function Publish() {
  return window['go']['platforms']['RodCSDN']['Publish']();
}

export function SetAccount(arg1) {
  return window['go']['platforms']['RodCSDN']['SetAccount'](arg1);
}

export function SetArticle(arg1) {
  return window['go']['platforms']['RodCSDN']['SetArticle'](arg1);
}

export function SetController(arg1, arg2) {
  return window['go']['platforms']['RodCSDN']['SetController'](arg1, arg2);
}

export function Start(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['platforms']['RodCSDN']['Start'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdatePlatformInfo() {
  return window['go']['platforms']['RodCSDN']['UpdatePlatformInfo']();
}
