// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthentication() {
  return window['go']['platforms']['RodCSDN']['CheckAuthentication']();
}

export function CheckConfig(arg1, arg2) {
  return window['go']['platforms']['RodCSDN']['CheckConfig'](arg1, arg2);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['platforms']['RodCSDN']['Init'](arg1, arg2, arg3);
}

export function LoadConfig(arg1) {
  return window['go']['platforms']['RodCSDN']['LoadConfig'](arg1);
}

export function LoadCookies() {
  return window['go']['platforms']['RodCSDN']['LoadCookies']();
}

export function Login() {
  return window['go']['platforms']['RodCSDN']['Login']();
}

export function OpenPage(arg1) {
  return window['go']['platforms']['RodCSDN']['OpenPage'](arg1);
}

export function RUN() {
  return window['go']['platforms']['RodCSDN']['RUN']();
}

export function Run() {
  return window['go']['platforms']['RodCSDN']['Run']();
}

export function SetConfig() {
  return window['go']['platforms']['RodCSDN']['SetConfig']();
}

export function SetCookies(arg1) {
  return window['go']['platforms']['RodCSDN']['SetCookies'](arg1);
}

export function UpdatePlatformInfo() {
  return window['go']['platforms']['RodCSDN']['UpdatePlatformInfo']();
}
