// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthentication() {
  return window['go']['platforms']['RodZhiHu']['CheckAuthentication']();
}

export function CheckConfig(arg1) {
  return window['go']['platforms']['RodZhiHu']['CheckConfig'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['platforms']['RodZhiHu']['Init'](arg1, arg2, arg3);
}

export function LoadConfig(arg1, arg2) {
  return window['go']['platforms']['RodZhiHu']['LoadConfig'](arg1, arg2);
}

export function LoadCookies() {
  return window['go']['platforms']['RodZhiHu']['LoadCookies']();
}

export function Login() {
  return window['go']['platforms']['RodZhiHu']['Login']();
}

export function OpenPage(arg1) {
  return window['go']['platforms']['RodZhiHu']['OpenPage'](arg1);
}

export function RUN() {
  return window['go']['platforms']['RodZhiHu']['RUN']();
}

export function Run() {
  return window['go']['platforms']['RodZhiHu']['Run']();
}

export function SetConfig(arg1) {
  return window['go']['platforms']['RodZhiHu']['SetConfig'](arg1);
}

export function SetCookies(arg1) {
  return window['go']['platforms']['RodZhiHu']['SetCookies'](arg1);
}

export function UpdatePlatformInfo() {
  return window['go']['platforms']['RodZhiHu']['UpdatePlatformInfo']();
}
