// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthentication() {
  return window['go']['platforms']['RodZhiHu']['CheckAuthentication']();
}

export function CheckConfig(arg1) {
  return window['go']['platforms']['RodZhiHu']['CheckConfig'](arg1);
}

export function HasAccount() {
  return window['go']['platforms']['RodZhiHu']['HasAccount']();
}

export function HasDBController() {
  return window['go']['platforms']['RodZhiHu']['HasDBController']();
}

export function HasRODController() {
  return window['go']['platforms']['RodZhiHu']['HasRODController']();
}

export function InitRod(arg1, arg2, arg3) {
  return window['go']['platforms']['RodZhiHu']['InitRod'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['platforms']['RodZhiHu']['LoadConfig']();
}

export function Login() {
  return window['go']['platforms']['RodZhiHu']['Login']();
}

export function OpenPage(arg1) {
  return window['go']['platforms']['RodZhiHu']['OpenPage'](arg1);
}

export function Publish() {
  return window['go']['platforms']['RodZhiHu']['Publish']();
}

export function SetAccount(arg1) {
  return window['go']['platforms']['RodZhiHu']['SetAccount'](arg1);
}

export function SetArticle(arg1) {
  return window['go']['platforms']['RodZhiHu']['SetArticle'](arg1);
}

export function SetController(arg1, arg2) {
  return window['go']['platforms']['RodZhiHu']['SetController'](arg1, arg2);
}

export function Start(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['platforms']['RodZhiHu']['Start'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdatePlatformInfo() {
  return window['go']['platforms']['RodZhiHu']['UpdatePlatformInfo']();
}
